---@module 'github_stats.dashboard.@types'
---@brief Type definitions for the dashboard/ subtree
---@description
--- Moved out of the flat `lua/github_stats/@types/` into a per-subdirectory
--- folder, per Arch&Coding.md's documented gap: dashboard/ is the one
--- subdirectory big enough (state.lua, render.lua, actions.lua, movement.lua,
--- detail.lua, layout.lua, init.lua) to justify owning its types instead of
--- sharing the plugin-wide folder. Consumed by dashboard/state.lua,
--- dashboard/render.lua, dashboard/actions.lua, dashboard/movement.lua.

---@class GHStats.DashboardState
---@field repos string[] List of repository identifiers
---@field current_index integer Currently selected repository index (1-based)
---@field scroll_offset integer Number of lines scrolled from top
---@field win_height integer Current window height in lines
---@field max_scroll integer Maximum allowed scroll offset
---@field last_render_time integer Timestamp of last render (ms)
---@field selected_index integer Currently selected repository (1-based)
---@field sort_by "clones"|"views"|"name"|"trend" Current sort criteria
---@field time_range string Current time range filter: "7d"/"30d"/"90d"/"max" (cycle presets, "max"/"all" both meaning the full stored duration) or any expression accepted by `github_stats.analytics.parse_time_range` (e.g. "3m", "since:2025-01-01", a date_presets name)
---@field is_open boolean Whether dashboard is currently displayed
---@field last_refresh integer Unix timestamp of last refresh
---@field auto_refresh_timer uv.uv_timer_t? Auto-refresh timer handle
---@field buffer integer? Dashboard buffer handle
---@field window integer? Dashboard window handle

--- Right-click context menu (nvzone/menu, a soft dependency). Only
--- controls whether the trigger and entries are offered; the
--- integration turns itself off when nvzone/menu is absent.
---@class GHStats.DashboardMenuConfig
---@field enable? boolean Offer the context menu at all (default true)

---@class GHStats.DashboardKeybindings
---@field navigate_down string Keybinding to navigate down
---@field navigate_up string Keybinding to navigate up
---@field show_details string Keybinding to show detailed view
---@field refresh_selected string Keybinding to refresh selected repo
---@field refresh_all string Keybinding to refresh all repos
---@field force_refresh string Keybinding to force refresh
---@field cycle_sort string Keybinding to cycle sort criteria
---@field cycle_time_range string Keybinding to cycle time range
---@field custom_time_range string Keybinding to prompt for a free-form time range expression
---@field max_time_range string Keybinding to jump straight to the maximum stored duration ("max")
---@field show_help string Keybinding to show help overlay
---@field quit string Keybinding to quit dashboard

---@class GHStats.DashboardConfig
---@field enabled? boolean Whether dashboard is enabled
---@field auto_open? boolean Whether to open the dashboard automatically on VimEnter
---@field refresh_interval_seconds? integer Auto-refresh interval
---@field sort_by? "clones"|"views"|"name"|"trend" Default sort criteria
---@field time_range? string Default time range filter: "7d"/"30d"/"90d"/"max"/"all" or any expression accepted by `github_stats.analytics.parse_time_range`
---@field trend_window_days? integer Days per trend comparison window: the last N complete days versus the N before them, independent of the displayed range (default 7)
---@field header_width? integer Content width between the header box's borders (default 72)
---@field sparkline_width? integer Width of a row's daily-breakdown sparkline, in characters (default 24)
---@field render_debounce_ms? integer Minimum time between dashboard renders in ms (default 50)
---@field theme? "default"|"minimal"|"compact" Display theme (reserved for future)
---@field menu? GHStats.DashboardMenuConfig Right-click context menu (nvzone/menu)
---@field keybindings? GHStats.DashboardKeybindings Customizable keybindings

--- The dashboard half of `GHStats.Config`: the fields the dashboard reads
--- without a fallback are guaranteed once the defaults are merged in.
--- `sort_by` and `time_range` belong here because `dashboard/state.lua`
--- ends its `or` chain at DEFAULTS -- an optional there leaves the chain
--- open, and `GHStats.DashboardState` declares both non-optional.
---@class GHStats.Dashboard.Resolved : GHStats.DashboardConfig
---@field enabled                  boolean
---@field refresh_interval_seconds integer
---@field sort_by                  "clones"|"views"|"name"|"trend"
---@field time_range               string

return {}
